### ISSUE TITLE
Manual. Help!

### ISSUE THREAD

**Issue by GorIvanov** [AnicetNgrt/jiro-nn#1]
I am new in Rust, and it is hard to figure out all without real manual, examples.

Is it possyble to get some example how to use this library?

I would like to see example for 2 dimentional data as input, like
```
[
[0.1,1,0.8,0.2,0.6....]
[0.1,1,0.8,0.2,0.6....]
[0.1,1,0.8,0.2,0.6....]
[0.1,1,0.8,0.2,0.6....]
]

```
and 1 dimensional array list as output [x,y]

So, for each input array  -  [x,y] output

```
[0.1,1,0.8,0.2,0.6....] -> output [x,y]
[0.1,1,0.8,0.2,0.6....] -> output [x,y]
[0.1,1,0.8,0.2,0.6....] -> output [x,y]
[0.1,1,0.8,0.2,0.6....] -> output [x,y]


```

**Comment by AnicetNgrt** [comment]
Hello,
A big new update with better documentation and simple examples will come out soon (before the 13th of July certainly, but I can't promise too much). I'll see if I can include your simple case, or at least I will answer by then with something that will be compatible with the new version. I could give you the code example now but my response would be outdated too soon.
Thanks for checking out my library

**Comment by AnicetNgrt** [comment]
@GorIvanov Look at the new [XOR example](https://github.com/AnicetNgrt/jiro-nn/blob/main/examples/xor/src/main.rs) which is very similar to your case. If you want more in depth information take a look at the other examples, and the docs : https://docs.rs/jiro_nn/latest/jiro_nn/

Thank you for checking my library :)
